<!-- BEGIN INFORMATIONBLOCK -->
<div id="informationbox" class="border_left_1">
	{BILDUPLOAD}
	{EXIFDATEN}
	{KUNDENSUCHEBOX}
	{KUNDENDATENBOX}
	{KUNDENGALERIENBOX}
	{GALERIEEINSTELLBOX}
</div>
<!-- END INFORMATIONBLOCK -->